const models = [

    { label : "コンクリートダムモデル_ダム+等高線-ENU.rvt", urn:"dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6MTcwMzEzX2hpc2hpZGEzLyVFMyU4MiVCMyVFMyU4MyVCMyVFMyU4MiVBRiVFMyU4MyVBQSVFMyU4MyVCQyVFMyU4MyU4OCVFMyU4MyU4MCVFMyU4MyVBMCVFMyU4MyVBMiVFMyU4MyU4NyVFMyU4MyVBQl8lRTMlODMlODAlRTMlODMlQTArJUU3JUFEJTg5JUU5JUFCJTk4JUU3JUI3JTlBLUVOVS5ydnQ"},

];

module.exports = {
   models
}